select current_date(), 2 + 3;


-- step 1

SELECT DEPTNO, ENAME, 
        CASE JOB WHEN 'CLERK' THEN SAL END CLERK,
        CASE JOB WHEN 'MANAGER' THEN SAL END MANAGER,
        CASE JOB WHEN 'SALESMAN' THEN SAL END SALESMAN,
        CASE JOB WHEN 'ANALYST' THEN SAL END ANALYST,
        CASE JOB WHEN 'PRESIDENT' THEN SAL END PRESIDENT,
        SAL
FROM     EMP
GROUP BY DEPTNO;

-- IF 사용
select deptno,
sum(if(job = "CLERK", SAL,"")) CLERK,
sum(if(job = "MANAGER", SAL,""))  MANAGER,
sum(if(job = "SALESMAN", SAL,""))  SALESMAN,
sum(if(job = "ANALYST", SAL,""))  ANALYST,
sum(if(job = "PRESIDENT", SAL,""))  PRESIDENT,
sum(sal)
from emp
group by deptno with rollup;


-- STEP2

SELECT DEPTNO,
        SUM(CASE JOB WHEN 'CLERK' THEN SAL END) CLERK,
        SUM(CASE JOB WHEN 'MANAGER' THEN SAL END) MANAGER,
        SUM(CASE JOB WHEN 'SALESMAN' THEN SAL END) SALESMAN,
        SUM(CASE JOB WHEN 'ANALYST' THEN SAL END) ANALYST,
        SUM(CASE JOB WHEN 'PRESIDENT' THEN SAL END) PRESIDENT,
        SUM(SAL)
FROM     EMP
GROUP BY DEPTNO WITH rollup;

SELECT DEPTNO,
        COUNT(CASE JOB WHEN 'CLERK' THEN SAL END) CLERK,
        COUNT(CASE JOB WHEN 'MANAGER' THEN SAL END) MANAGER,
        COUNT(CASE JOB WHEN 'SALESMAN' THEN SAL END) SALESMAN,
        COUNT(CASE JOB WHEN 'ANALYST' THEN SAL END) ANALYST,
        COUNT(CASE JOB WHEN 'PRESIDENT' THEN SAL END) PRESIDENT,
        COUNT(SAL)
FROM     EMP
GROUP BY DEPTNO WITH rollup;


-- INLINE VIEW
SELECT DEPTNO, SUM(CLERK), SUM(MANAGER), SUM(SALESMAN), SUM(ANALYST), SUM(PRESIDENT), SUM(SAL)
FROM (
    SELECT DEPTNO, ENAME,
        CASE JOB WHEN 'CLERK' THEN SAL END CLERK,
        CASE JOB WHEN 'MANAGER' THEN SAL END MANAGER,
        CASE JOB WHEN 'SALESMAN' THEN SAL END SALESMAN,
        CASE JOB WHEN 'ANALYST' THEN SAL END ANALYST,
        CASE JOB WHEN 'PRESIDENT' THEN SAL END PRESIDENT,
        SAL
    FROM     EMP
) e
GROUP BY DEPTNO WITH ROLLUP;

-- COUNT 해보기
SELECT DEPTNO, COUNT(CLERK), COUNT(MANAGER), COUNT(SALESMAN), COUNT(ANALYST), COUNT(PRESIDENT), COUNT(SAL)
FROM (
    SELECT DEPTNO, ENAME,
        CASE JOB WHEN 'CLERK' THEN SAL END CLERK,
        CASE JOB WHEN 'MANAGER' THEN SAL END MANAGER,
        CASE JOB WHEN 'SALESMAN' THEN SAL END SALESMAN,
        CASE JOB WHEN 'ANALYST' THEN SAL END ANALYST,
        CASE JOB WHEN 'PRESIDENT' THEN SAL END PRESIDENT,
        SAL
    FROM     EMP
) e
GROUP BY DEPTNO WITH ROLLUP;

CREATE VIEW V_EMP_DEPT_JOB 
AS     SELECT DEPTNO, ENAME,
        CASE JOB WHEN 'CLERK' THEN SAL END CLERK,
        CASE JOB WHEN 'MANAGER' THEN SAL END MANAGER,
        CASE JOB WHEN 'SALESMAN' THEN SAL END SALESMAN,
        CASE JOB WHEN 'ANALYST' THEN SAL END ANALYST,
        CASE JOB WHEN 'PRESIDENT' THEN SAL END PRESIDENT,
        SAL
    FROM     EMP; 
    

SELECT DEPTNO, SUM(CLERK), SUM(MANAGER), SUM(SALESMAN), 
SUM(ANALYST), SUM(PRESIDENT), SUM(SAL)
FROM v_emp_dept_job
GROUP BY DEPTNO WITH ROLLUP;

SELECT DEPTNO, COUNT(CLERK), COUNT(MANAGER), COUNT(SALESMAN), 
COUNT(ANALYST), COUNT(PRESIDENT), COUNT(SAL)
FROM v_emp_dept_job
GROUP BY DEPTNO WITH ROLLUP;

-- VIEW를 쓰는 이유: SQL의 재사용성



CREATE OR REPLACE VIEW V_SIMPLE_EMP
AS     SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10;
    
INSERT INTO V_SIMPLE_EMP VALUES(9000, '김재환', 3500, 10);

-- 평균 급여가 최대인 부서번호, 평균 급여
-- 2가지 방법
 -- 1번 
SELECT DEPTNO, AVG(SAL) salAvg FROM EMP
GROUP BY DEPTNO
ORDER BY AVG(SAL) desc
limit 1;

select deptno, avg(sal) from emp 
group by deptno 
order by avg(sal) desc 
limit 1;
 
SELECT DEPTNO, AVG(SAL)
-- 부서별 평균급여
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) = (
                
                SELECT MAX(SAL)
                FROM (
                    SELECT AVG(SAL) sal
                    FROM EMP
                    GROUP BY DEPTNO
                    ) a
);
 
-- 그룹함수의 중첩을 지원하지 않음
--  SELECT MAX(AVG(SAL))
--  FROM EMP
--  GROUP BY DEPTNO;
 
 -- 2번
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
ORDER BY AVG(SAL) DESC
LIMIT 1;

-- 집계함수의 중복은 안된다
